services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSKEY=passkey
      - SECRET_KEY=secret
      - GEMINI_MODEL=gemini-2.5-flash
      - GEMINI_API_KEY=your-gemini-api-key
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - AI_CHAT_ENABLED=true
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - SESSION_TIMEOUT_SECONDS=10
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0.15-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   container_name: redisinsight
  #   ports:
  #     - "5540:5540"
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDISINSIGHT_REDIS_HOST=redis
  #     - REDISINSIGHT_REDIS_PORT=6379
  #   restart: unless-stopped

volumes:
  redis_data:
