services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSKEY=passkey
      - SECRET_KEY=secret
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=us-east-1
      - Q_MODEL_ID=amazon.titan-text-express-v1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0.15-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  redis_data:
