services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSKEY=passkey
      - SECRET_KEY=secret
      - GEMINI_MODEL=gemini-2.0-flash
      - GEMINI_API_KEY=your_gemini_api_key
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - AI_CHAT_ENABLED=true
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7.0.15-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

volumes:
  redis_data:
